my:
  server:
    addr:  192.168.195.203
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://${my.server.addr}:3316/tarena_pigeon?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: pigeon_user
    password: PigeonPas$8x
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
  # redis
  redis:
    host: dev-redis.tctm.life
    port: 6379
    password: "teduPMNlzjfDiaK"
    database: 8
    jedis:
      pool:
        max-active: 8
        min-idle: 5
        max-idle: 8
        max-wait: PT15M
        time-between-eviction-runs: PT15M
excel:
  path:
    task: "F:/excel/"
    white-list: "F:/excel/"
