dispatcher:
  assembler_sms: true
  mock: true
  notice_sms_ali: true
  sms_ali_pigeon_provider_code: ALI_SMS
json:
  provider: fastJson
monitor:
  impl: default
mybatis:
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
rocket:
  message_charset: UTF-8
  name_server_address: 192.168.195.244:9876
  publish_debug: true
  publish_group: publish_group
  retry_times_when_send_failed: 5
  topic: mnmp_test
server:
  port: 8000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: PigeonPas$8x
    url: jdbc:mysql://192.168.195.203:3316/tarena_pigeon?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: pigeon_user
